networks:
  # define network to communicate between container 
  Ecommerce_net:
    name: Ecommerce_net
    driver: bridge

volumes:
  #blind volume for persistance storage
  ecommerce_service_vol:
  auth_service_vol:
  apigateway_service_vol:
  payment_service_vol:
  remainder_service_vol:
  rabbitmq_server_vol:
  postgres_db_vol:
  redis_db_vol:
  mongodb_vol:

services:
  #define service or container 
  postgres_service:
      image: postgres:latest
      container_name: postgres_db
      restart: unless-stopped
      networks:
        - Ecommerce_net
      env_file:
        - ./envirnoment/.env.postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_db_vol:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d POSTGRES_db"]
        interval: 10s
        timeout: 5s
        retries: 5
  
  mongodb_service:
    image: mongo:latest
    container_name: mongodb_service
    networks:
      - Ecommerce_net
    ports:
      # - "27017:27017"
      - "27018:27017"
    volumes:
      - mongodb_vol:/data/db
    env_file:
      - ./envirnoment/.env.mongodb
        
    command: >
      mongod --logpath /var/log/mongodb/mongod.log --quiet --logappend
      --setParameter logComponentVerbosity='{network: {verbosity: -1}}' 
      --setParameter logLevel=0
    
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis_service:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6380:6379"
    networks:
      - Ecommerce_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540" 
    environment:
      - RI_ACCEPT_EULA=yes
      - RI_AUTO_DISCOVER_REDIS=redis_service:6379
    networks:
      - Ecommerce_net
    depends_on:
      redis_service:
        condition: service_healthy
    volumes:
      - redis_db_vol:/data
    restart: unless-stopped

  rabbitmq_service:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_server
    restart: unless-stopped
    networks:
      - Ecommerce_net
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - rabbitmq_server_vol:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5


  auth_service: 
    image: sarojdockerworkspace/auth_service:latest
    build: 
      context: ./02_Auth_microservice
      dockerfile: dockerfile
    container_name: auth_service
    env_file:
      - ./envirnoment/.env
      - ./envirnoment/.env.auth
    networks:
      - Ecommerce_net
    ports:
      - "3001:3001"
    volumes:
      - ./02_Auth_microservice:/Ecommerce/Backend/authservice
      - auth_service_vol:/Ecommerce/Backend/authservice/node_modules
    depends_on:
      postgres_service: 
        condition: service_healthy
      rabbitmq_service: 
        condition: service_healthy

  ecommerce_service: 
    image:  sarojdockerworkspace/ecommerce_service:latest
    build: 
      context: ./02_Ecomerce
      dockerfile: dockerfile
    container_name: ecommerce_service
    env_file:
      - ./envirnoment/.env
      - ./envirnoment/.env.ecomerce
    networks:
      - Ecommerce_net
    ports:
      - "3003:3003"
    volumes:
      - ./02_Ecomerce:/Ecommerce/backend
      - ecommerce_service_vol:/Ecommerce/backend/node_modules   

    depends_on:
      postgres_service:
        condition: service_healthy

    restart: unless-stopped
    command: >
      sh -c "
        npm install &&
        cd src && 
        npx sequelize-cli db:create --env development || true  &&
        npx sequelize-cli db:migrate --env development &&
        npx sequelize-cli  db:seed:all --env development &&   
        npm start
      "
  
  payment_service:
    image:  sarojdockerworkspace/payment_service:latest
    container_name: payment_service
    build:
      context: ./05_Payment_microservice
      dockerfile: dockerfile
    env_file:
      - ./envirnoment/.env
      - ./envirnoment/.env.payment
    networks:
      - Ecommerce_net
    ports:
      - "3009:3009"
    volumes:
      - ./05_Payment_microservice:/Ecommerce/backend/payment_service
      - payment_service_vol:/Ecommerce/backend/payment_service/node_modules
    restart: unless-stopped
    depends_on:
      postgres_service:
        condition: service_healthy
      rabbitmq_service:
        condition: service_healthy
      
    command: >
      sh -c "
        npm install &&
        cd src && 
        npx sequelize-cli db:create --env development || true &&
        npx sequelize-cli db:migrate --env development &&
        npm start
      "

 
  api_gateway_service:
    image: sarojdockerworkspace/api_gateway:latest
    container_name: api_gateway_service
    build: ./01_ApiGateway
    env_file:
      - ./envirnoment/.env
      - ./envirnoment/.env.apigateway
    networks:
      - Ecommerce_net
    ports:
      - "3000:3000"
    volumes:
      - ./01_ApiGateway:/Ecommerce/backend/apigateway_service
      - apigateway_service_vol:/Ecommerce/backend/apigateway_service/node_modules
    command: >
      sh -c "
        npm install &&
        npm start
      "
  
  remainder_service:
    image: sarojdockerworkspace/remainder_backend:latest
    container_name: remainder_service
    build:
      context: ./04_Remainder_microservice
      dockerfile: dockerfile
    env_file:
      - ./envirnoment/.env
      - ./envirnoment/.env.remainder
    networks:
      - Ecommerce_net
    ports:
      - "3004:3004"
    volumes:
      - ./04_Remainder_microservice:/Ecommerce/backend/remainder_service
      - remainder_service_vol:/Ecommerce/backend/remainder_service/node_modules
    restart: unless-stopped
    depends_on:
      rabbitmq_service:
        condition: service_healthy
      postgres_service:
        condition: service_healthy
    command: >
      sh -c "
        npm install &&
        cd src &&
        npx sequelize-cli db:create --env development || true &&
        npx sequelize-cli db:migrate --env development  && 
        npx sequelize-cli db:seed  --env development || true &&
        npm start
      "