apiVersion: apps/v1
kind: Deployment
metadata:
  name: remainder-dep
  namespace: marketmandu-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: remainder-dep
  template:
    metadata:
      labels:
        app: remainder-dep
    spec:
      containers:
      - name: remainder-dep-container
        image: sarojdockerworkspace/marketmandu-remainder_microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        envFrom:
          - configMapRef:
              name: mm-remainder-config
          - secretRef:
              name: mm-remainder-secrets
        env:
         
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: PORT


          - name: INTERNAL_SERVER_TOKEN
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: INTERNAL_SERVER_TOKEN
                
          - name: EMAIL_ID
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: EMAIL_ID

          - name: EMAIL_SENDER
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-secrets
                key: EMAIL_SENDER

          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name:  mm-ecommerce-secrets
                key: EMAIL_PASS

          - name: PAYMENT_BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: PAYMENT_BACKEND_URL


          - name: MESSAGE_BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: MESSAGE_BROKER_URL


          - name: EXCHANGE_NAME
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: EXCHANGE_NAME

          - name: REMINDER_BINDING_KEY
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: REMINDER_BINDING_KEY

          - name: FORTEND_URL
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: FORTEND_URL

          - name: AUTH_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: AUTH_SERVICE_URL

          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: REDIS_URL
          
          - name: PRIVATEJWTRefersh
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: PRIVATEJWTRefersh

          - name: PRIVATEJWT
            valueFrom:
              configMapKeyRef:
                name: mm-remainder-config
                key: PRIVATEJWT

        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
        limits:
          memory: "300Mi"
          cpu: "250m"