apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dep
  namespace: marketmandu-ns
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dep
  template:
    metadata:
      labels:
        app: postgres-dep
    spec:
      containers:
        - name: postgres-dep
          image: postgres:14
          envFrom:
            - configMapRef:
                name: mm-postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi