apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-dep
  namespace: marketmandu-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-dep
  template:
    metadata:
      labels:
        app: ecomerce-dep
    spec:
      initContainers:
        - name: db-migrate
          image: sarojdockerworkspace/marketmandu-ecomerce_microservice:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm install &&
              cd src &&
              npx sequelize-cli db:create --env development || true &&
              npx sequelize-cli db:migrate --env development &&
              npx sequelize-cli db:seed:all --env development || true
          envFrom:
            - configMapRef:
                name: mm-ecommerce-config
            - secretRef:
                name: mm-ecommerce-secrets

      containers:
        - name: ecomerce-dep-container
          image: sarojdockerworkspace/marketmandu-ecomerce_microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: mm-ecommerce-config
            - secretRef:
                name: mm-ecommerce-secrets
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: PORT
            - name: salt
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: salt
            - name: RefreshPRIVATEJWT
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: RefreshPRIVATEJWT
            - name: PRIVATEJWT
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: PRIVATEJWT
            - name: INTERNAL_SERVER_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: INTERNAL_SERVER_TOKEN
            - name: EMAIL_ID
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: EMAIL_ID
            - name: PAYMENT_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: PAYMENT_BACKEND_URL
            - name: APIGATEWAY_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: APIGATEWAY_BACKEND_URL
            - name: FORTEND_SUCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: FORTEND_SUCESS_URL
            - name: MESSAGE_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: MESSAGE_BROKER_URL
            - name: CHANNEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: CHANNEL_NAME
            - name: EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: EXCHANGE_NAME
            - name: REMINDER_BINDING_KEY
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: REMINDER_BINDING_KEY
            - name: ECOOMERCE_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: mm-ecommerce-config
                  key: ECOOMERCE_QUEUE
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: EMAIL_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: AWS_REGION
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: BUCKET_NAME
            - name: CLOUDFRONT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: CLOUDFRONT_DOMAIN
            - name: CLOUDFRONT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: CLOUDFRONT_PRIVATE_KEY
            - name: CLOUDFRONT_KEY_PAIR_ID
              valueFrom:
                secretKeyRef:
                  name: mm-ecommerce-secrets
                  key: CLOUDFRONT_KEY_PAIR_ID
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "250m"